### ISSUE TITLE
Feedback Code-Review

### ISSUE THREAD

**Issue by perellano** [tlangdun/getter#44]
Eure SW hat bei mir funktioniert. Ich konnte es builden und laufen lassen. Generel ist noch nicht viel zu sehen weil ich keine Infos habe betreffend Test Username.
- Euer Readme darf mehr Infos beinhalten. Siehe: [gute Beispiele](https://github.com/matiassingers/awesome-readme)
- Achitektur und Link zum SonarQube fehlen.
- .env Datei beinhalten viele "geheime" Infos. -> Das ist nicht OK. Ihr müsst das eine Lösung finden.
- Wo läuft euer App damit man es testen kann mit Testuser?
- Die Test dürfen umfangreicher sein

Design vom der Hauptseite sieht schön aus. Bin gespannt was hinter dem Login sich verbirgt.

**Comment by tlangdun** [comment]
Vielen Dank für das review!

Die env Datei gehört natürlich nicht ins Repo... Da ist uns ein Fehler unterlaufen. Danke für den Hinweis.
Ist mit Architektur ein UML diagramm gemeint?
Bezüglich SonarCloud muss ich noch schauen, dass auch Sie Zugriff darauf haben.

Wir versuchen sobald wie möglich eine testbare Version auf www.getter.ch zu pushen

**Comment by tlangdun** [comment]
ich habe im readme noch sonarcloud hinzugefügt:
https://sonarcloud.io/project/overview?id=tlangdun_getter
